java_binary(
    name = "hello",
    srcs = ["Hello.java"],
    main_class = "org.scode.bazelplay.Hello",
    deps = [
        "//src/java/org/scode/bazelplay/lib:greeter",
        "//src/proto:person_java_proto",
    ],
)
