java_proto_library(
  name = "person_java_proto",
  visibility = ["//visibility:public"],
  deps = [":person_proto"],
)

proto_library(
  name = "person_proto",
  srcs = ["person.proto"],
  deps = [
  ],
)