name: CI
on: [push]
jobs:
  bazel_test:
    name: bazel test
    runs-on: ubuntu-latest
    steps:
    - name: setup go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: install bazelisk
      run: |
        go get github.com/bazelbuild/bazelisk

    - name: checkout code
      uses: actions/checkout@v1

    - name: bazel test //...
      run: |
        $(go env GOPATH)/bin/bazelisk test //...
